# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMVVMSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMVVMSample
  
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'RxMVVMSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
