platform :ios, '12.0'

target 'RxMVVMSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMVVMSample
  
  pod 'RxSwift',    '~> 6.0'
  pod 'RxCocoa',    '~> 6.0'

  target 'RxMVVMSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
