//
// Organization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Organization: Codable, Equatable, Hashable {

    public var avatarUrl: String?
    public var gravatarId: String?
    public var _id: Int
    public var login: String
    public var type: String
    public var url: String

    public init(avatarUrl: String?, gravatarId: String?, _id: Int, login: String, type: String, url: String) {
        self.avatarUrl = avatarUrl
        self.gravatarId = gravatarId
        self._id = _id
        self.login = login
        self.type = type
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case avatarUrl = "avatar_url"
        case gravatarId = "gravatar_id"
        case _id = "id"
        case login
        case type
        case url
    }


}

