//
// Organization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Organization: Codable, Equatable, Hashable {

    public var avatarUrl: String?
    public var gravatarId: String?
    public var id: Int
    public var login: String
    public var type: String
    public var url: String

    public init(avatarUrl: String? = nil, gravatarId: String? = nil, id: Int, login: String, type: String, url: String) {
        self.avatarUrl = avatarUrl
        self.gravatarId = gravatarId
        self.id = id
        self.login = login
        self.type = type
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatarUrl = "avatar_url"
        case gravatarId = "gravatar_id"
        case id
        case login
        case type
        case url
    }

}
