//
// PublicRepo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PublicRepo: Codable, Equatable, Hashable {

    public var description: String?
    public var fork: Bool
    public var fullName: String
    public var htmlUrl: String?
    public var id: Int
    public var name: String
    public var owner: Owner
    public var _private: Bool
    public var url: String

    public init(description: String? = nil, fork: Bool, fullName: String, htmlUrl: String? = nil, id: Int, name: String, owner: Owner, _private: Bool, url: String) {
        self.description = description
        self.fork = fork
        self.fullName = fullName
        self.htmlUrl = htmlUrl
        self.id = id
        self.name = name
        self.owner = owner
        self._private = _private
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case fork
        case fullName = "full_name"
        case htmlUrl = "html_url"
        case id
        case name
        case owner
        case _private = "private"
        case url
    }

}
