//
// Repo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Repo: Codable, Equatable, Hashable {

    public var cloneUrl: String
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var createdAt: String
    public var description: String?
    public var fork: Bool
    public var forks: Int
    public var forksCount: Int
    public var fullName: String
    public var gitUrl: String
    public var hasDownloads: Bool
    public var hasIssues: Bool
    public var hasWiki: Bool
    public var homepage: String?
    public var htmlUrl: String
    public var id: Int
    public var language: String?
    public var masterBranch: String?
    public var mirrorUrl: String?
    public var name: String
    public var openIssues: Int
    public var openIssuesCount: Int
    public var organization: Organization?
    public var owner: Owner
    public var parent: Parent?
    public var _private: Bool
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var pushedAt: String
    public var size: Int
    public var source: Source?
    public var sshUrl: String
    public var svnUrl: String?
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var updatedAt: String
    public var url: String
    public var watchers: Int
    public var watchersCount: Int

    public init(cloneUrl: String, createdAt: String, description: String? = nil, fork: Bool, forks: Int, forksCount: Int, fullName: String, gitUrl: String, hasDownloads: Bool, hasIssues: Bool, hasWiki: Bool, homepage: String? = nil, htmlUrl: String, id: Int, language: String? = nil, masterBranch: String? = nil, mirrorUrl: String? = nil, name: String, openIssues: Int, openIssuesCount: Int, organization: Organization? = nil, owner: Owner, parent: Parent? = nil, _private: Bool, pushedAt: String, size: Int, source: Source? = nil, sshUrl: String, svnUrl: String? = nil, updatedAt: String, url: String, watchers: Int, watchersCount: Int) {
        self.cloneUrl = cloneUrl
        self.createdAt = createdAt
        self.description = description
        self.fork = fork
        self.forks = forks
        self.forksCount = forksCount
        self.fullName = fullName
        self.gitUrl = gitUrl
        self.hasDownloads = hasDownloads
        self.hasIssues = hasIssues
        self.hasWiki = hasWiki
        self.homepage = homepage
        self.htmlUrl = htmlUrl
        self.id = id
        self.language = language
        self.masterBranch = masterBranch
        self.mirrorUrl = mirrorUrl
        self.name = name
        self.openIssues = openIssues
        self.openIssuesCount = openIssuesCount
        self.organization = organization
        self.owner = owner
        self.parent = parent
        self._private = _private
        self.pushedAt = pushedAt
        self.size = size
        self.source = source
        self.sshUrl = sshUrl
        self.svnUrl = svnUrl
        self.updatedAt = updatedAt
        self.url = url
        self.watchers = watchers
        self.watchersCount = watchersCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cloneUrl = "clone_url"
        case createdAt = "created_at"
        case description
        case fork
        case forks
        case forksCount = "forks_count"
        case fullName = "full_name"
        case gitUrl = "git_url"
        case hasDownloads = "has_downloads"
        case hasIssues = "has_issues"
        case hasWiki = "has_wiki"
        case homepage
        case htmlUrl = "html_url"
        case id
        case language
        case masterBranch = "master_branch"
        case mirrorUrl = "mirror_url"
        case name
        case openIssues = "open_issues"
        case openIssuesCount = "open_issues_count"
        case organization
        case owner
        case parent
        case _private = "private"
        case pushedAt = "pushed_at"
        case size
        case source
        case sshUrl = "ssh_url"
        case svnUrl = "svn_url"
        case updatedAt = "updated_at"
        case url
        case watchers
        case watchersCount = "watchers_count"
    }

}
