//
// Asset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Asset: Codable {

    public var contentType: String?
    public var createdAt: String?
    public var downloadCount: Double?
    public var _id: Double?
    public var label: String?
    public var name: String?
    public var size: Double?
    public var state: String?
    public var updatedAt: String?
    public var uploader: Any?
    public var url: String?

    public init(contentType: String?, createdAt: String?, downloadCount: Double?, _id: Double?, label: String?, name: String?, size: Double?, state: String?, updatedAt: String?, uploader: Any?, url: String?) {
        self.contentType = contentType
        self.createdAt = createdAt
        self.downloadCount = downloadCount
        self._id = _id
        self.label = label
        self.name = name
        self.size = size
        self.state = state
        self.updatedAt = updatedAt
        self.uploader = uploader
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case contentType = "content_type"
        case createdAt = "created_at"
        case downloadCount = "download_count"
        case _id = "id"
        case label
        case name
        case size
        case state
        case updatedAt = "updated_at"
        case uploader
        case url
    }


}

