//
// AssetPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct AssetPatch: Codable {

    public var label: String?
    public var name: String?

    public init(label: String?, name: String?) {
        self.label = label
        self.name = name
    }


}

