//
// Blob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Blob: Codable {

    public enum Encoding: String, Codable {
        case utf8 = "utf-8"
        case base64 = "base64"
    }
    public var content: String?
    public var encoding: Encoding?
    public var sha: String?
    public var size: Int?

    public init(content: String?, encoding: Encoding?, sha: String?, size: Int?) {
        self.content = content
        self.encoding = encoding
        self.sha = sha
        self.size = size
    }


}

