//
// Blobs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Blobs: Codable {

    public var sha: String?

    public init(sha: String?) {
        self.sha = sha
    }


}

