//
// Branch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Branch: Codable {

    public var links: Any?
    public var commit: Any?
    public var name: String?

    public init(links: Any?, commit: Any?, name: String?) {
        self.links = links
        self.commit = commit
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case links = "_links"
        case commit
        case name
    }


}

