//
// CompareCommits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CompareCommits: Codable {

    public var aheadBy: Int?
    public var baseCommit: Any?
    public var behindBy: Int?
    public var commits: [Any]?
    public var diffUrl: String?
    public var files: [Any]?
    public var htmlUrl: String?
    public var patchUrl: String?
    public var permalinkUrl: String?
    public var status: String?
    public var totalCommits: Int?
    public var url: String?

    public init(aheadBy: Int?, baseCommit: Any?, behindBy: Int?, commits: [Any]?, diffUrl: String?, files: [Any]?, htmlUrl: String?, patchUrl: String?, permalinkUrl: String?, status: String?, totalCommits: Int?, url: String?) {
        self.aheadBy = aheadBy
        self.baseCommit = baseCommit
        self.behindBy = behindBy
        self.commits = commits
        self.diffUrl = diffUrl
        self.files = files
        self.htmlUrl = htmlUrl
        self.patchUrl = patchUrl
        self.permalinkUrl = permalinkUrl
        self.status = status
        self.totalCommits = totalCommits
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case aheadBy = "ahead_by"
        case baseCommit = "base_commit"
        case behindBy = "behind_by"
        case commits
        case diffUrl = "diff_url"
        case files
        case htmlUrl = "html_url"
        case patchUrl = "patch_url"
        case permalinkUrl = "permalink_url"
        case status
        case totalCommits = "total_commits"
        case url
    }


}

