//
// CreateFileBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CreateFileBody: Codable {

    public var committer: Any?
    public var content: String?
    public var message: String?

    public init(committer: Any?, content: String?, message: String?) {
        self.committer = committer
        self.content = content
        self.message = message
    }


}

