//
// CreateDownload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CreateDownload: Codable {

    public var accesskeyid: String?
    public var acl: String?
    public var bucket: String?
    public var contentType: String?
    public var _description: String?
    public var downloadCount: Int?
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var expirationdate: String?
    public var htmlUrl: String?
    public var _id: Int?
    public var mimeType: String?
    public var name: String?
    public var path: String?
    public var policy: String?
    public var _prefix: String?
    public var redirect: Bool?
    public var s3Url: String?
    public var signature: String?
    public var size: Int?
    public var url: String?

    public init(accesskeyid: String?, acl: String?, bucket: String?, contentType: String?, _description: String?, downloadCount: Int?, expirationdate: String?, htmlUrl: String?, _id: Int?, mimeType: String?, name: String?, path: String?, policy: String?, _prefix: String?, redirect: Bool?, s3Url: String?, signature: String?, size: Int?, url: String?) {
        self.accesskeyid = accesskeyid
        self.acl = acl
        self.bucket = bucket
        self.contentType = contentType
        self._description = _description
        self.downloadCount = downloadCount
        self.expirationdate = expirationdate
        self.htmlUrl = htmlUrl
        self._id = _id
        self.mimeType = mimeType
        self.name = name
        self.path = path
        self.policy = policy
        self._prefix = _prefix
        self.redirect = redirect
        self.s3Url = s3Url
        self.signature = signature
        self.size = size
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case accesskeyid
        case acl
        case bucket
        case contentType = "content_type"
        case _description = "description"
        case downloadCount = "download_count"
        case expirationdate
        case htmlUrl = "html_url"
        case _id = "id"
        case mimeType = "mime_type"
        case name
        case path
        case policy
        case _prefix = "prefix"
        case redirect
        case s3Url = "s3_url"
        case signature
        case size
        case url
    }


}

