//
// Downloads.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Downloads: Codable {

    public var contentType: String?
    public var _description: String?
    public var downloadCount: Int?
    public var htmlUrl: String?
    public var _id: Int?
    public var name: String?
    public var size: Int?
    public var url: String?

    public init(contentType: String?, _description: String?, downloadCount: Int?, htmlUrl: String?, _id: Int?, name: String?, size: Int?, url: String?) {
        self.contentType = contentType
        self._description = _description
        self.downloadCount = downloadCount
        self.htmlUrl = htmlUrl
        self._id = _id
        self.name = name
        self.size = size
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case contentType = "content_type"
        case _description = "description"
        case downloadCount = "download_count"
        case htmlUrl = "html_url"
        case _id = "id"
        case name
        case size
        case url
    }


}

