//
// EditTeam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EditTeam: Codable {

    public enum Permission: String, Codable {
        case pull = "pull"
        case push = "push"
        case admin = "admin"
    }
    public var name: String?
    public var permission: Permission?

    public init(name: String?, permission: Permission?) {
        self.name = name
        self.permission = permission
    }


}

