//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Event: Codable {

    public var actor: Any?
    public var commitId: String?
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var createdAt: String?
    public var event: String?
    public var issue: Any?
    public var url: String?

    public init(actor: Any?, commitId: String?, createdAt: String?, event: String?, issue: Any?, url: String?) {
        self.actor = actor
        self.commitId = commitId
        self.createdAt = createdAt
        self.event = event
        self.issue = issue
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case actor
        case commitId = "commit_id"
        case createdAt = "created_at"
        case event
        case issue
        case url
    }


}

