//
// IssueBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct IssueBody: Codable {

    public var assignee: String?
    public var body: String?
    public var labels: [String]?
    public var milestone: Double?
    public var title: String?

    public init(assignee: String?, body: String?, labels: [String]?, milestone: Double?, title: String?) {
        self.assignee = assignee
        self.body = body
        self.labels = labels
        self.milestone = milestone
        self.title = title
    }


}

