//
// Label.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Label: Codable {

    public var color: String?
    public var name: String?
    public var url: String?

    public init(color: String?, name: String?, url: String?) {
        self.color = color
        self.name = name
        self.url = url
    }


}

