//
// MergePullBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MergePullBody: Codable {

    public var commitMessage: String?

    public init(commitMessage: String?) {
        self.commitMessage = commitMessage
    }

    public enum CodingKeys: String, CodingKey { 
        case commitMessage = "commit_message"
    }


}

