//
// PatchGist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PatchGist: Codable {

    public var _description: String?
    public var files: Any?

    public init(_description: String?, files: Any?) {
        self._description = _description
        self.files = files
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case files
    }


}

