//
// PullRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PullRequest: Codable {

    public var links: Any?
    public var additions: Int?
    public var base: Any?
    public var body: String?
    public var changedFiles: Int?
    public var closedAt: String?
    public var comments: Int?
    public var commits: Int?
    public var createdAt: String?
    public var deletions: Int?
    public var diffUrl: String?
    public var head: Any?
    public var htmlUrl: String?
    public var issueUrl: String?
    public var mergeCommitSha: String?
    public var mergeable: Bool?
    public var merged: Bool?
    public var mergedAt: String?
    public var mergedBy: Any?
    public var number: Int?
    public var patchUrl: String?
    public var state: String?
    public var title: String?
    public var updatedAt: String?
    public var url: String?
    public var user: Any?

    public init(links: Any?, additions: Int?, base: Any?, body: String?, changedFiles: Int?, closedAt: String?, comments: Int?, commits: Int?, createdAt: String?, deletions: Int?, diffUrl: String?, head: Any?, htmlUrl: String?, issueUrl: String?, mergeCommitSha: String?, mergeable: Bool?, merged: Bool?, mergedAt: String?, mergedBy: Any?, number: Int?, patchUrl: String?, state: String?, title: String?, updatedAt: String?, url: String?, user: Any?) {
        self.links = links
        self.additions = additions
        self.base = base
        self.body = body
        self.changedFiles = changedFiles
        self.closedAt = closedAt
        self.comments = comments
        self.commits = commits
        self.createdAt = createdAt
        self.deletions = deletions
        self.diffUrl = diffUrl
        self.head = head
        self.htmlUrl = htmlUrl
        self.issueUrl = issueUrl
        self.mergeCommitSha = mergeCommitSha
        self.mergeable = mergeable
        self.merged = merged
        self.mergedAt = mergedAt
        self.mergedBy = mergedBy
        self.number = number
        self.patchUrl = patchUrl
        self.state = state
        self.title = title
        self.updatedAt = updatedAt
        self.url = url
        self.user = user
    }

    public enum CodingKeys: String, CodingKey { 
        case links = "_links"
        case additions
        case base
        case body
        case changedFiles = "changed_files"
        case closedAt = "closed_at"
        case comments
        case commits
        case createdAt = "created_at"
        case deletions
        case diffUrl = "diff_url"
        case head
        case htmlUrl = "html_url"
        case issueUrl = "issue_url"
        case mergeCommitSha = "merge_commit_sha"
        case mergeable
        case merged
        case mergedAt = "merged_at"
        case mergedBy = "merged_by"
        case number
        case patchUrl = "patch_url"
        case state
        case title
        case updatedAt = "updated_at"
        case url
        case user
    }


}

