//
// PullUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PullUpdate: Codable {

    public var body: String?
    public var state: String?
    public var title: String?

    public init(body: String?, state: String?, title: String?) {
        self.body = body
        self.state = state
        self.title = title
    }


}

