//
// RepoCommit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RepoCommit: Codable {

    public var author: Any?
    public var committer: Any?
    public var message: String?
    public var parents: [Any]?
    public var sha: String?
    public var tree: Any?
    public var url: String?

    public init(author: Any?, committer: Any?, message: String?, parents: [Any]?, sha: String?, tree: Any?, url: String?) {
        self.author = author
        self.committer = committer
        self.message = message
        self.parents = parents
        self.sha = sha
        self.tree = tree
        self.url = url
    }


}

