//
// SearchRepositoriesByKeyword.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SearchRepositoriesByKeyword: Codable {

    public var repositories: [Any]?

    public init(repositories: [Any]?) {
        self.repositories = repositories
    }


}

