//
// SearchIssuesByKeyword.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SearchIssuesByKeyword: Codable {

    public var issues: [Any]?

    public init(issues: [Any]?) {
        self.issues = issues
    }


}

