//
// SearchUsersByKeyword.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SearchUsersByKeyword: Codable {

    public var users: [Any]?

    public init(users: [Any]?) {
        self.users = users
    }


}

