//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Tag: Codable {

    public var message: String?
    public var object: Any?
    public var sha: String?
    public var tag: String?
    public var tagger: Any?
    public var url: String?

    public init(message: String?, object: Any?, sha: String?, tag: String?, tagger: Any?, url: String?) {
        self.message = message
        self.object = object
        self.sha = sha
        self.tag = tag
        self.tagger = tagger
        self.url = url
    }


}

