//
// TeamMembership.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TeamMembership: Codable {

    public var state: String?
    public var url: String?

    public init(state: String?, url: String?) {
        self.state = state
        self.url = url
    }


}

