platform :ios, '12.0'

target 'RxSimpleSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSimpleSample
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'

  target 'RxSimpleSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
