platform :ios, '12.0'

target 'FluxWithRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FluxWithRxSwift
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'
  pod 'GitHub', :path => '../../GitHub'

  target 'FluxWithRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
