# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FluxPlusExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FluxPlusExample
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'
  pod 'GitHub', :path => '../../GitHub'

  target 'FluxPlusExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
