//
// PublicRepo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PublicRepo: Codable, Equatable, Hashable {

    public var _description: String?
    public var fork: Bool
    public var fullName: String
    public var htmlUrl: String?
    public var _id: Int
    public var name: String
    public var owner: Owner
    public var _private: Bool
    public var url: String

    public init(_description: String?, fork: Bool, fullName: String, htmlUrl: String?, _id: Int, name: String, owner: Owner, _private: Bool, url: String) {
        self._description = _description
        self.fork = fork
        self.fullName = fullName
        self.htmlUrl = htmlUrl
        self._id = _id
        self.name = name
        self.owner = owner
        self._private = _private
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case fork
        case fullName = "full_name"
        case htmlUrl = "html_url"
        case _id = "id"
        case name
        case owner
        case _private = "private"
        case url
    }


}

