//
// CommentBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CommentBody: Codable {

    public var body: String?

    public init(body: String?) {
        self.body = body
    }


}

