//
// Deployment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Deployment: Codable {

    public var _description: String?
    public var payload: Any?
    public var ref: String?

    public init(_description: String?, payload: Any?, ref: String?) {
        self._description = _description
        self.payload = payload
        self.ref = ref
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case payload
        case ref
    }


}

