//
// Milestone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Milestone: Codable {

    public enum State: String, Codable {
        case _open = "open"
        case closed = "closed"
    }
    public var closedIssues: Int?
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var createdAt: String?
    public var creator: Any?
    public var _description: String?
    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var dueOn: String?
    public var number: Int?
    public var openIssues: Int?
    public var state: State?
    public var title: String?
    public var url: String?

    public init(closedIssues: Int?, createdAt: String?, creator: Any?, _description: String?, dueOn: String?, number: Int?, openIssues: Int?, state: State?, title: String?, url: String?) {
        self.closedIssues = closedIssues
        self.createdAt = createdAt
        self.creator = creator
        self._description = _description
        self.dueOn = dueOn
        self.number = number
        self.openIssues = openIssues
        self.state = state
        self.title = title
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case closedIssues = "closed_issues"
        case createdAt = "created_at"
        case creator
        case _description = "description"
        case dueOn = "due_on"
        case number
        case openIssues = "open_issues"
        case state
        case title
        case url
    }


}

