//
// OrgTeamsPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct OrgTeamsPost: Codable {

    public enum Permission: String, Codable {
        case pull = "pull"
        case push = "push"
        case admin = "admin"
    }
    public var name: String?
    public var permission: Permission?
    public var repoNames: [String]?

    public init(name: String?, permission: Permission?, repoNames: [String]?) {
        self.name = name
        self.permission = permission
        self.repoNames = repoNames
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case permission
        case repoNames = "repo_names"
    }


}

