//
// PostGist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PostGist: Codable {

    public var _description: String?
    public var files: Any?
    public var _public: Bool?

    public init(_description: String?, files: Any?, _public: Bool?) {
        self._description = _description
        self.files = files
        self._public = _public
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case files
        case _public = "public"
    }


}

