//
// PullsCommentPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PullsCommentPost: Codable {

    public var body: String?
    public var commitId: String?
    public var path: String?
    public var position: Double?

    public init(body: String?, commitId: String?, path: String?, position: Double?) {
        self.body = body
        self.commitId = commitId
        self.path = path
        self.position = position
    }

    public enum CodingKeys: String, CodingKey { 
        case body
        case commitId = "commit_id"
        case path
        case position
    }


}

