//
// PullsPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PullsPost: Codable {

    public var base: String?
    public var body: String?
    public var head: String?
    public var title: String?

    public init(base: String?, body: String?, head: String?, title: String?) {
        self.base = base
        self.body = body
        self.head = head
        self.title = title
    }


}

