//
// RateLimit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RateLimit: Codable {

    public var rate: Any?

    public init(rate: Any?) {
        self.rate = rate
    }


}

