//
// SearchUserByEmail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SearchUserByEmail: Codable {

    public var user: Any?

    public init(user: Any?) {
        self.user = user
    }


}

