//
// CommitBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CommitBody: Codable {

    public var body: String?
    /** Deprecated - Use position parameter instead. */
    public var line: String?
    /** Line number in the file to comment on. Defaults to null. */
    public var number: String?
    /** Relative path of the file to comment on. */
    public var path: String?
    /** Line index in the diff to comment on. */
    public var position: Int?
    /** SHA of the commit to comment on. */
    public var sha: String?

    public init(body: String?, line: String?, number: String?, path: String?, position: Int?, sha: String?) {
        self.body = body
        self.line = line
        self.number = number
        self.path = path
        self.position = position
        self.sha = sha
    }


}

