//
// ContentsPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ContentsPath: Codable {

    public var links: Any?
    public var content: String?
    public var encoding: String?
    public var gitUrl: String?
    public var htmlUrl: String?
    public var name: String?
    public var path: String?
    public var sha: String?
    public var size: Int?
    public var type: String?
    public var url: String?

    public init(links: Any?, content: String?, encoding: String?, gitUrl: String?, htmlUrl: String?, name: String?, path: String?, sha: String?, size: Int?, type: String?, url: String?) {
        self.links = links
        self.content = content
        self.encoding = encoding
        self.gitUrl = gitUrl
        self.htmlUrl = htmlUrl
        self.name = name
        self.path = path
        self.sha = sha
        self.size = size
        self.type = type
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case links = "_links"
        case content
        case encoding
        case gitUrl = "git_url"
        case htmlUrl = "html_url"
        case name
        case path
        case sha
        case size
        case type
        case url
    }


}

