//
// CreateFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CreateFile: Codable {

    public var commit: Any?
    public var content: Any?

    public init(commit: Any?, content: Any?) {
        self.commit = commit
        self.content = content
    }


}

