//
// DeleteFileBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DeleteFileBody: Codable {

    public var committer: Any?
    public var message: String?
    public var sha: String?

    public init(committer: Any?, message: String?, sha: String?) {
        self.committer = committer
        self.message = message
        self.sha = sha
    }


}

