//
// DeleteFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DeleteFile: Codable {

    public var commit: Any?
    public var content: String?

    public init(commit: Any?, content: String?) {
        self.commit = commit
        self.content = content
    }


}

