//
// Events.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Events: Codable {

    public var actor: Any?
    public var createdAt: Any?
    public var _id: Int?
    public var org: Any?
    public var payload: Any?
    public var _public: Bool?
    public var repo: Any?
    public var type: String?

    public init(actor: Any?, createdAt: Any?, _id: Int?, org: Any?, payload: Any?, _public: Bool?, repo: Any?, type: String?) {
        self.actor = actor
        self.createdAt = createdAt
        self._id = _id
        self.org = org
        self.payload = payload
        self._public = _public
        self.repo = repo
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case actor
        case createdAt = "created_at"
        case _id = "id"
        case org
        case payload
        case _public = "public"
        case repo
        case type
    }


}

