//
// ForkBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ForkBody: Codable {

    public var organization: String?

    public init(organization: String?) {
        self.organization = organization
    }


}

