//
// GitCommit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct GitCommit: Codable {

    public var author: Any?
    public var message: String?
    public var parents: String?
    public var tree: String?

    public init(author: Any?, message: String?, parents: String?, tree: String?) {
        self.author = author
        self.message = message
        self.parents = parents
        self.tree = tree
    }


}

