//
// GitRefPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct GitRefPatch: Codable {

    public var force: Bool?
    public var sha: String?

    public init(force: Bool?, sha: String?) {
        self.force = force
        self.sha = sha
    }


}

