//
// HeadBranch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct HeadBranch: Codable {

    public var object: Any?
    public var ref: String?
    public var url: String?

    public init(object: Any?, ref: String?, url: String?) {
        self.object = object
        self.ref = ref
        self.url = url
    }


}

