//
// HookBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct HookBody: Codable {

    public var active: Bool?
    public var addEvents: [String]?

    public init(active: Bool?, addEvents: [String]?) {
        self.active = active
        self.addEvents = addEvents
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case addEvents = "add_events"
    }


}

