//
// Markdown.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Markdown: Codable {

    public var context: String?
    public var mode: String?
    public var text: String?

    public init(context: String?, mode: String?, text: String?) {
        self.context = context
        self.mode = mode
        self.text = text
    }


}

