//
// MergesConflict.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MergesConflict: Codable {

    /** Error message */
    public var message: String?

    public init(message: String?) {
        self.message = message
    }


}

