//
// MergesSuccessful.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MergesSuccessful: Codable {

    public var author: Any?
    public var commentsUrl: String?
    public var commit: Any?
    public var committer: Any?
    public var merged: Bool?
    public var message: String?
    public var parents: [Any]?
    public var sha: String?
    public var url: String?

    public init(author: Any?, commentsUrl: String?, commit: Any?, committer: Any?, merged: Bool?, message: String?, parents: [Any]?, sha: String?, url: String?) {
        self.author = author
        self.commentsUrl = commentsUrl
        self.commit = commit
        self.committer = committer
        self.merged = merged
        self.message = message
        self.parents = parents
        self.sha = sha
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case author
        case commentsUrl = "comments_url"
        case commit
        case committer
        case merged
        case message
        case parents
        case sha
        case url
    }


}

