//
// MergesBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MergesBody: Codable {

    public var base: String?
    public var commitMessage: String?
    public var head: String?

    public init(base: String?, commitMessage: String?, head: String?) {
        self.base = base
        self.commitMessage = commitMessage
        self.head = head
    }

    public enum CodingKeys: String, CodingKey { 
        case base
        case commitMessage = "commit_message"
        case head
    }


}

