//
// Merge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Merge: Codable {

    public var merged: Bool?
    public var message: String?
    public var sha: String?

    public init(merged: Bool?, message: String?, sha: String?) {
        self.merged = merged
        self.message = message
        self.sha = sha
    }


}

