//
// Notifications.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Notifications: Codable {

    public var _id: Int?
    public var lastReadAt: String?
    public var reason: String?
    public var repository: Any?
    public var subject: Any?
    public var unread: Bool?
    public var updatedAt: String?
    public var url: String?

    public init(_id: Int?, lastReadAt: String?, reason: String?, repository: Any?, subject: Any?, unread: Bool?, updatedAt: String?, url: String?) {
        self._id = _id
        self.lastReadAt = lastReadAt
        self.reason = reason
        self.repository = repository
        self.subject = subject
        self.unread = unread
        self.updatedAt = updatedAt
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case lastReadAt = "last_read_at"
        case reason
        case repository
        case subject
        case unread
        case updatedAt = "updated_at"
        case url
    }


}

