//
// OrganizationAsTeamMember.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct OrganizationAsTeamMember: Codable {

    public var errors: [Any]?
    public var message: String?

    public init(errors: [Any]?, message: String?) {
        self.errors = errors
        self.message = message
    }


}

