//
// ParticipationStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ParticipationStats: Codable {

    public var all: [Int]?
    public var owner: [Int]?

    public init(all: [Int]?, owner: [Int]?) {
        self.all = all
        self.owner = owner
    }


}

