//
// PatchOrg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PatchOrg: Codable {

    /** Billing email address. This address is not publicized. */
    public var billingEmail: String?
    public var company: String?
    /** Publicly visible email address. */
    public var email: String?
    public var location: String?
    public var name: String?

    public init(billingEmail: String?, company: String?, email: String?, location: String?, name: String?) {
        self.billingEmail = billingEmail
        self.company = company
        self.email = email
        self.location = location
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case billingEmail = "billing_email"
        case company
        case email
        case location
        case name
    }


}

