//
// PutSubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PutSubscription: Codable {

    public var createdAt: String?
    public var ignored: Bool?
    public var reason: Any?
    public var subscribed: Bool?
    public var threadUrl: String?
    public var url: String?

    public init(createdAt: String?, ignored: Bool?, reason: Any?, subscribed: Bool?, threadUrl: String?, url: String?) {
        self.createdAt = createdAt
        self.ignored = ignored
        self.reason = reason
        self.subscribed = subscribed
        self.threadUrl = threadUrl
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case ignored
        case reason
        case subscribed
        case threadUrl = "thread_url"
        case url
    }


}

