//
// RefsBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RefsBody: Codable {

    public var ref: String?
    public var sha: String?

    public init(ref: String?, sha: String?) {
        self.ref = ref
        self.sha = sha
    }


}

