//
// Release.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Release: Codable {

    public var assets: [Any]?
    public var assetsUrl: String?
    public var author: Any?
    public var body: String?
    public var createdAt: String?
    public var draft: Bool?
    public var htmlUrl: String?
    public var _id: Int?
    public var name: String?
    public var prerelease: Bool?
    public var publishedAt: String?
    public var tagName: String?
    public var tarballUrl: String?
    public var targetCommitish: String?
    public var uploadUrl: String?
    public var url: String?
    public var zipballUrl: String?

    public init(assets: [Any]?, assetsUrl: String?, author: Any?, body: String?, createdAt: String?, draft: Bool?, htmlUrl: String?, _id: Int?, name: String?, prerelease: Bool?, publishedAt: String?, tagName: String?, tarballUrl: String?, targetCommitish: String?, uploadUrl: String?, url: String?, zipballUrl: String?) {
        self.assets = assets
        self.assetsUrl = assetsUrl
        self.author = author
        self.body = body
        self.createdAt = createdAt
        self.draft = draft
        self.htmlUrl = htmlUrl
        self._id = _id
        self.name = name
        self.prerelease = prerelease
        self.publishedAt = publishedAt
        self.tagName = tagName
        self.tarballUrl = tarballUrl
        self.targetCommitish = targetCommitish
        self.uploadUrl = uploadUrl
        self.url = url
        self.zipballUrl = zipballUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case assets
        case assetsUrl = "assets_url"
        case author
        case body
        case createdAt = "created_at"
        case draft
        case htmlUrl = "html_url"
        case _id = "id"
        case name
        case prerelease
        case publishedAt = "published_at"
        case tagName = "tag_name"
        case tarballUrl = "tarball_url"
        case targetCommitish = "target_commitish"
        case uploadUrl = "upload_url"
        case url
        case zipballUrl = "zipball_url"
    }


}

