//
// RepoEdit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RepoEdit: Codable {

    public var _description: String?
    public var hasDownloads: Bool?
    public var hasIssues: Bool?
    public var hasWiki: Bool?
    public var homepage: String?
    public var name: String?
    public var _private: Bool?

    public init(_description: String?, hasDownloads: Bool?, hasIssues: Bool?, hasWiki: Bool?, homepage: String?, name: String?, _private: Bool?) {
        self._description = _description
        self.hasDownloads = hasDownloads
        self.hasIssues = hasIssues
        self.hasWiki = hasWiki
        self.homepage = homepage
        self.name = name
        self._private = _private
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case hasDownloads = "has_downloads"
        case hasIssues = "has_issues"
        case hasWiki = "has_wiki"
        case homepage
        case name
        case _private = "private"
    }


}

