//
// Subscribition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Subscribition: Codable {

    /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
    public var createdAt: String?
    public var ignored: Bool?
    public var reason: String?
    public var repositoryUrl: String?
    public var subscribed: Bool?
    public var url: String?

    public init(createdAt: String?, ignored: Bool?, reason: String?, repositoryUrl: String?, subscribed: Bool?, url: String?) {
        self.createdAt = createdAt
        self.ignored = ignored
        self.reason = reason
        self.repositoryUrl = repositoryUrl
        self.subscribed = subscribed
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case ignored
        case reason
        case repositoryUrl = "repository_url"
        case subscribed
        case url
    }


}

