//
// SubscribitionBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SubscribitionBody: Codable {

    public var ignored: Bool?
    public var subscribed: Bool?

    public init(ignored: Bool?, subscribed: Bool?) {
        self.ignored = ignored
        self.subscribed = subscribed
    }


}

