//
// Tags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Tags: Codable {

    /** String of the tag message. */
    public var message: String?
    /** String of the SHA of the git object this is tagging. */
    public var object: String?
    public var tag: String?
    public var tagger: Any?
    /** String of the type of the object we’re tagging. Normally this is a commit but it can also be a tree or a blob. */
    public var type: String?

    public init(message: String?, object: String?, tag: String?, tagger: Any?, type: String?) {
        self.message = message
        self.object = object
        self.tag = tag
        self.tagger = tagger
        self.type = type
    }


}

