//
// Tree.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Tree: Codable {

    public var sha: String?
    public var tree: [Any]?
    public var url: String?

    public init(sha: String?, tree: [Any]?, url: String?) {
        self.sha = sha
        self.tree = tree
        self.url = url
    }


}

