//
// Trees.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Trees: Codable {

    public var baseTree: String?
    /** SHA1 checksum ID of the object in the tree. */
    public var sha: String?
    public var tree: [Any]?
    public var url: String?

    public init(baseTree: String?, sha: String?, tree: [Any]?, url: String?) {
        self.baseTree = baseTree
        self.sha = sha
        self.tree = tree
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case baseTree = "base_tree"
        case sha
        case tree
        case url
    }


}

