//
// UserKeysPost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct UserKeysPost: Codable {

    public var key: String?
    public var title: String?

    public init(key: String?, title: String?) {
        self.key = key
        self.title = title
    }


}

